[package]
edition = "2021"
name = "prisma-models"
version = "0.0.0"

[dependencies]
psl.workspace = true
itertools = "0.10"
prisma-value = { path = "../../libs/prisma-value" }
bigdecimal = "0.3"
thiserror = "1.0"
getrandom = { version = "0.2" }
uuid = { workspace = true, optional = true }
cuid = { git = "https://github.com/jkomyno/cuid-rust", branch = "jkomyno/wasm32", optional = true }
nanoid = { version = "0.4.0", optional = true }
chrono = { version = "0.4.6", features = ["serde"] }

[features]
default = ["all"]
all = ["wasm_generators", "sys_generators"]

# Support for generating default UUID, CUID, nanoid and datetime values.
sys_generators = []
wasm_generators = ["cuid", "uuid", "nanoid", "getrandom/js"]

cuid = ["dep:cuid"]
nanoid = ["dep:nanoid"]
uuid = ["uuid/v4"]
