[package]
edition = "2021"
name = "prisma-models"
version = "0.0.0"

[dependencies]
psl.workspace = true
itertools = "0.10"
prisma-value = { path = "../../libs/prisma-value" }
bigdecimal = "0.3"
thiserror = "1.0"

uuid = { workspace = true, optional = true }
cuid = { version = "1.2", optional = true }
cuid2 = { version = "0.1.2", optional = true } 
nanoid = { version = "0.4.0", optional = true }
chrono = { version = "0.4.6", features = ["serde"] }

[features]
# Support for generating default UUID, CUID, nanoid and datetime values. This
# implies random number generation works, so it won't compile on targets like
# wasm32.
# Note: this feature flag should be removed. It's fully possible to implement
# some of these default generators in wasm32. We just need to conditionally
# import the `getrandom` crate with the `js` feature when on `wasm32` arch.
default_generators = ["uuid/v4", "cuid", "cuid2", "nanoid"]
