[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[dependencies]
psl.workspace = true
rustc-hash = "1.1.0"
once_cell = "1"
prisma-models = { path = "../prisma-models" }

[dev-dependencies]
codspeed-criterion-compat = "1.1.0"

[[bench]]
name = "schema_builder_bench"
harness = false
