[package]
name = "query-engine-node-api"
version = "0.1.0"
edition = "2021"

[lib]
doc = false
crate-type = ["cdylib"]
name = "query_engine"

[features]
default = ["js-drivers"]
vendored-openssl = ["sql-connector/vendored-openssl"]
js-drivers = ["sql-connector/js-drivers"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
query-connector = { path = "../connectors/query-connector" }
psl.workspace = true
prisma-models = { path = "../prisma-models" }

thiserror = "1"
connection-string.workspace = true 
url = "2"
serde_json.workspace = true
serde.workspace = true

futures = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
napi.workspace = true
napi-derive.workspace = true
js-drivers = { path = "../js-drivers" }
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
tracing-futures = "0.2"
tracing-opentelemetry = "0.17.3"
opentelemetry = { version = "0.17"}
sql-connector = { path = "../connectors/sql-query-connector", package = "sql-query-connector" }
query-core = { path = "../core" }
query-engine-metrics = {path = "../metrics"}
request-handlers = { path = "../request-handlers" }
user-facing-errors = { path = "../../libs/user-facing-errors" }
quaint.workspace = true
tokio.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.84" }
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
napi-build = "1"
